disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - force_cast

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - explicit_init
  - first_where
  - implicit_return
  - modifier_order
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

included:
  - Sources

excluded:
  - .build
  - DerivedData
  - Pods
  - Carthage

identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j

type_name:
  min_length: 3
  max_length: 60

reporter: "xcode"
